Scrubbing Preview
jarnedemeulemeester/findroid pull request #295
Opened 2023-02-16 19:36 UTC by Faywyrr

Add scrubbing preview with Jellyscrub plugin

Demo :
https://user-images.githubusercontent.com/51246506/219468275-22c4d8b6-b16e-49bd-9ab9-263604c991ed.mp4

2023-02-16 20:55 UTC, jarnedemeulemeester commented
Nice work!

2023-02-17 17:47 UTC, Faywyrr commented
@OpenSourceSimon look at the last commit

2023-02-17 17:51 UTC, OpenSourceSimon commented
> @OpenSourceSimon look at the last commit

Awesome thanks!

2023-02-20 21:42 UTC, jarnedemeulemeester requested changes
Overall pretty happy with the implementation. It's very smooth and looks good. 
I didn't encounter any bugs :smile: 

I do however have some proposed changes. 

I have a commit ready, if you agree with the changes I will push it.

2023-02-20 21:42 UTC, jarnedemeulemeester commented on app/phone/src/main/res/layout/exo_player_control_view.xml
> +            tools:visibility="visible">
Is it required to have a `FrameLayout` around the `ImageView`?
Seems to work exactly the same when only using an `ImageView` (with the properties of the `FrameLayout`)

2023-02-20 21:42 UTC, jarnedemeulemeester commented on app/phone/src/main/java/dev/jdtech/jellyfin/utils/PreviewScrubListener.kt
> +        val maxX = parent.width - parent.paddingRight - layoutParams.rightMargin
`layoutParams.rightMargin` seems to always be `0`? With or without the `FrameLayout`.

2023-02-20 21:42 UTC, jarnedemeulemeester commented on app/phone/src/main/java/dev/jdtech/jellyfin/utils/PreviewScrubListener.kt
> +    private val currentTrickPlay: LiveData<BifData?>
```suggestion
    private val currentTrickPlay: StateFlow<BifData?>
```
I would like to get rid of LiveData in the future so I suggest we use SateFlow here instead.

2023-02-20 21:58 UTC, jarnedemeulemeester commented
Seems like one of my comments went missing... 

I also would move the retrieval of the trick play data to `onMediaItemTransition`. That way it only retrieves it for the current item and does it async. 
For example right now if there are 80 items queued with each 2MB of trick play data then the player needs to do 160 extra requests for a total of 160MB of data. This could block the player for quite some time.

But as I've mentioned I have a commit ready :smile:

2023-02-20 22:58 UTC, Faywyrr commented on app/phone/src/main/res/layout/exo_player_control_view.xml
> +            tools:visibility="visible">
So much the better if it works without the framelayout

2023-02-20 22:58 UTC, Faywyrr commented on app/phone/src/main/java/dev/jdtech/jellyfin/utils/PreviewScrubListener.kt
> +        val maxX = parent.width - parent.paddingRight - layoutParams.rightMargin
so you might as well take it off :)

2023-02-20 22:58 UTC, Faywyrr commented on app/phone/src/main/java/dev/jdtech/jellyfin/utils/PreviewScrubListener.kt
> +    private val currentTrickPlay: LiveData<BifData?>
👍

2023-02-20 22:58 UTC, Faywyrr commented
@jarnedemeulemeester Yes I suspected that loading all the previews in cache would surely be a bit problematic. For the rest it's great if it works as well or better, I let you commit it. Thanks for your speed!

2023-02-20 23:27 UTC, jarnedemeulemeester approved these changes

2023-02-20 23:29 UTC, jarnedemeulemeester commented
@Faywyrr I recommend you test again to make sure everything still works.

If it's all good then I think we can merge this!

2023-02-20 23:55 UTC, Faywyrr commented
@jarnedemeulemeester on my side it works fine !

2023-02-21 18:46 UTC, merged