feat: show episode size in extra info
jarnedemeulemeester/findroid pull request #477
Opened 2023-08-18 23:23 UTC by Natanel-Shitrit

## Feature Preview
![image](https://github.com/jarnedemeulemeester/findroid/assets/65548905/9e5c323b-b129-4be2-8a7e-79c1d138f1b7)

## Related Issues
- Resolves #452

2023-08-20 10:32 UTC, jarnedemeulemeester requested changes

2023-08-20 10:32 UTC, jarnedemeulemeester commented on app/phone/src/main/res/layout/episode_bottom_sheet.xml
> +            tools:visibility="visible" />
I think this group can be removed as it does not seem to be used.

2023-08-20 10:32 UTC, jarnedemeulemeester commented on app/phone/src/main/res/layout/episode_bottom_sheet.xml
> +            android:gravity="bottom"
`drawablePadding` and `gravity` are not required here and can be removed.

2023-08-21 19:41 UTC, jarnedemeulemeester approved these changes

2023-08-21 19:41 UTC, merged

2023-08-21 22:56 UTC, Rdkang commented
thank you @Natanel-Shitrit  🙌 💜