Add season downloads
jarnedemeulemeester/findroid pull request #492
Opened 2023-08-25 14:35 UTC by Jcuhfehl

Fixes #73

2023-08-25 15:12 UTC, Natanel-Shitrit commented
- #461

2023-08-25 16:19 UTC, Jcuhfehl commented
Marking as draft because I want to add a prompt to ask if the user wants to download all episodes or only unwatched ones

2023-08-27 17:25 UTC, Jcuhfehl commented
Added the prompt and fixed the linting issues, so it's ready for review

2023-09-01 20:11 UTC, Yash-Garg requested changes

2023-09-01 20:11 UTC, Yash-Garg commented on app/phone/src/main/java/dev/jdtech/jellyfin/fragments/SeasonFragment.kt
> +import dev.jdtech.jellyfin.R
Can use the core resources like below:

```suggestion
import dev.jdtech.jellyfin.R
import dev.jdtech.jellyfin.core.R as CoreR
```

2023-09-01 20:11 UTC, Yash-Garg commented on app/phone/src/main/java/dev/jdtech/jellyfin/fragments/SeasonFragment.kt
> +                        dev.jdtech.jellyfin.core.R.id.action_download_season -> {
Can change the resource IDs to use the same:

```suggestion
                        CoreR.id.action_download_season -> {
```

2023-09-01 20:11 UTC, Yash-Garg commented on app/phone/src/main/java/dev/jdtech/jellyfin/fragments/SeasonFragment.kt
> +            .setTitle(dev.jdtech.jellyfin.core.R.string.preparing_download)
```suggestion
            .setTitle(CoreR.string.preparing_download)
```

2023-09-01 20:11 UTC, Yash-Garg commented on app/phone/src/main/java/dev/jdtech/jellyfin/fragments/SeasonFragment.kt
> +            .setTitle(dev.jdtech.jellyfin.core.R.string.downloading_error)
```suggestion
            .setTitle(CoreR.string.downloading_error)
```

2023-09-01 20:11 UTC, Yash-Garg commented on app/phone/src/main/java/dev/jdtech/jellyfin/fragments/SeasonFragment.kt
> +            .setPositiveButton(dev.jdtech.jellyfin.core.R.string.download_season_dialog_download_all) { _, _ ->
```suggestion
            .setTitle(CoreR.string.download_season_dialog_title)
            .setMessage(CoreR.string.download_season_dialog_question)
            .setPositiveButton(CoreR.string.download_season_dialog_download_all) { _, _ ->
```

2023-09-01 20:11 UTC, Yash-Garg commented on app/phone/src/main/java/dev/jdtech/jellyfin/fragments/SeasonFragment.kt
> +            .setNegativeButton(dev.jdtech.jellyfin.core.R.string.download_season_dialog_download_unwatched) { _, _ ->
```suggestion
            .setNegativeButton(CoreR.string.download_season_dialog_download_unwatched) { _, _ ->
```

2024-04-03 14:37 UTC, Panda260 commented
Very, very cool and useful PR I would love to see this PR get merged! is there a time estimate when it will get merged? @jarnedemeulemeester

2024-04-13 22:58 UTC, EinNiki commented
Hey, why hasn't the PR feature been accepted yet?

2024-06-09 20:38 UTC, suyashmahar commented
Since it's been a while, i merged it locally and built it. If you want to use it, here is the link: https://drive.google.com/file/d/1eBN_y4uoGTBLc9dakjYskYKWlKTmsRVp/view?usp=sharing

2024-07-08 21:50 UTC, formeo14 commented
Thanks for your own build. 
But why isn't t merged yet?

2024-07-11 19:37 UTC, suyashmahar commented
> Please be careful when downloading random apk's :)
Honestly, it is pretty easy to build it if you don't trust the APK and was a huge QoL improvement.

2024-11-30 01:46 UTC, Teravla commented
Hello, guy ;)

Any News about this PR ? ;)

2024-11-30 11:54 UTC, formeo14 commented
> Any News about this PR ? ;)


I don't think @jarnedemeulemeester will add it. The repository has 33 PRs, but none have been merged. It could be that he doesn't have enough time. So, I believe we'll need to wait for someone to fork the project and continue the work. It's also unfortunate that some people have invested their time in creating PRs, but they seem to be ignored. Use Findroid Bleeding it has some PRs like this merged, this PR is more then one year old.

2024-11-30 12:22 UTC, jarnedemeulemeester commented
@Teravla @formeo14 my apologies for not being so active on GitHub. 
I am currently converting the whole project from views to compose. This change will have a big impact on almost all open PRs, that's one of the reasons many have not been merged.

This PR in particular touches the UI layer which will be completely rewritten.

Also  the way downloads work right now may need to completely change to be more robust. But that's a conversation for an other time.

2024-11-30 18:35 UTC, formeo14 commented
@jarnedemeulemeester, everything is fine. The current version of Findroid is working well, and with Findroid Bleeding, several PRs have been merged. I think the UI is quite good, so I wouldn't change it unless the programming becomes too difficult or could potentially cause issues in the future. However, I agree with the comment that the downloads need to be rewritten because, although the download manager works, if the phone loses connection in the last few moments I have to restart the download because it doesn't save the state of the partially downloaded file.

If you plan to make a significant UI change, could you please mention it somewhere on this Repository (e.g. a roadmap/ pinned issue) so that people who also use their free time to implement features know that their work might not be added immediately and they should wait for the UI update?

2025-06-28 14:12 UTC, eblieb commented
Did this ever get added?

2025-06-29 13:47 UTC, jeremicmilan commented
@formeo14, with @jarnedemeulemeester's change #1002, does it mean you can move forward with your change?
Thank you both for doing this!

2025-11-11 20:08 UTC, Silver-3 commented
both findroid "debug" and "bleeding" either dont work or doesnt download episodes. anything updated for 2025?

2026-06-23 12:47 UTC, midasvo commented
> both findroid "debug" and "bleeding" either dont work or doesnt download episodes. anything updated for 2025?

i've forked into findroid-ce, https://github.com/midasvo/findroid-ce, beware i heavily rely on claude since i don't have much time either

2026-08-02 18:42 UTC, Jcuhfehl commented
This isn't relevant anymore after the rewrite

2026-08-02 18:42 UTC, closed without merging