Update README.md for PiP mode
jarnedemeulemeester/findroid pull request #502
Opened 2023-09-01 17:56 UTC by Natanel-Shitrit

2023-09-01 18:09 UTC, Jcuhfehl commented
Semi related: I wouldn't call mpv player a "new" feature anymore

2023-09-01 18:11 UTC, Natanel-Shitrit commented
> Semi related: I wouldn't call mpv player a "new" feature anymore

Updated readme and PR name :)

2023-09-02 09:29 UTC, jarnedemeulemeester requested changes
Good catch! The README definitely needs an update.

While you're correcting it I would also use the correct naming from now on.

2023-09-02 09:29 UTC, jarnedemeulemeester commented on README.md
> +- Picture in picture mode
```suggestion
- Picture-in-picture mode
```

2023-09-02 09:29 UTC, jarnedemeulemeester commented on README.md
> +- MPV Player
```suggestion
- mpv
```

2023-09-02 09:38 UTC, jarnedemeulemeester approved these changes

2023-09-02 09:38 UTC, merged